[[glossary]]
== Glossary

[glossary]
API:: application programming interface, a connection between computers or between computer programs; it is a type of software interface, offering a service to other pieces of software
CDN:: content delivery network, a geographically distributed network of proxy servers and their data centers
CSP:: Content Security Policy, a computer security standard introduced to prevent cross-site scripting (XSS), clickjacking and other code injection attacks resulting from execution of malicious content in the trusted web page context.
CSS:: Cascading Style Sheets, a style sheet language used for describing the presentation of a document written in a markup language such as HTML.
GUI:: graphical user interface, a form of user interface (UI) that allows users to interact with electronic devices through graphical icons and audio indicator such as primary notation, instead of text-based user interfaces, typed command labels or text navigation
HTML:: HyperText Markup Language, the standard markup language for documents designed to be displayed in a web browser
JS:: JavaScript, a programming language that is one of the core technologies of the World Wide Web, alongside HTML and CSS,
JSON:: JavaScript Object Notation, an open standard file format and data interchange format that uses human-readable text to store and transmit data objects consisting of attribute–value pairs and arrays (or other serializable values)
PWA:: progressive web app(lication), a type of application software delivered through the web, built using common web technologies including HTML, CSS, JavaScript, and WebAssembly; it is intended to work on any platform that uses a standards-compliant browser, including both desktop and mobile devices
SEO:: search engine optimization, the process of improving the quality and quantity of website traffic to a website or a web page from search engines
static web page:: a web page that is delivered to the user’s web browser exactly as stored, in contrast to dynamic web pages which are generated by a web application
TUI:: terminal user interface *or* text-based user interface, a retronym describing a type of user interface (UI) common as an early form of human–computer interaction, before the advent of graphical user interfaces (GUIs)
UI:: user interface, the space where interactions between humans and machines occur
UX:: user experience, how a user interacts with and experiences a product, system or service
