Performance
===========

== Asset optimization

=== Compression

* for all static content, will be compressed with https://en.wikipedia.org/wiki/Brotli[Brotli] and https://en.wikipedia.org/wiki/Gzip[GZip] compression (if Brotli isn’t provided by our CDN, bug them until they do because browser support has existed across the board for years)

=== Minification

* all scripts should be minified; mangling is also prefered
* all styles should be minified; selectors and media queries should be combined using a tool
* images should be compressed and used the best format for the job (however, not all information should be blindly stripped suchas color profile and license information)

=== Audio/video formats

* prefer vector/scalable graphics to raster graphics in most cases as they are usually smaller and scale to all screen sizes
* provide optimized image/video formats (i.e. `*.avif`, `*.jxl`, `*.webp`, `*.jp(2|x)`) (when the format is better or smaller than older formats with broad support, because this isn’t always the case, especially images with small dimensions)
* provide fallback image/video formats with broad support (i.e. `*.jpg`, `*.png`) and prefering at least one level of progressive decoding

== Prefetch

* provide `preload` or `prefetch` or `modulepreload` headers/links for often-used or guaranteed to be needed assets
* provide `preconnect` or `dns-prefetch` headers/links for all remote servers connected to

== Deferred loading

* ‘lazily’ load and defer assets when possible (e.g. `<img loading="lazy">`, `<script defer>`)

== Loading indicators

* pages will have a visually interesting and attractive loading spinner/throbber while loading content; a good spinner is distracting/mesmerizing enough that a user’s perceived performance is higher with than without
